import 'angular';
import './plugins/vinilla.js';
import './vendors/cssua.js';
import 'angular-resource';
import 'angular-sanitize';
import 'gsap';
import 'gsap/src/uncompressed/utils/Draggable.js';
import 'gsap/src/uncompressed/plugins/ScrollToPlugin.js';
import './plugins/ThrowPropsPlugin.min.js';
import './plugins/DrawSVGPlugin.min-modif.js'
import 'lodash';
import './plugins/angular-ui-utils/ui-utils.js';
import 'angular-animate';
import 'angular-google-maps';
import './plugins/isteven-multi-select'
import 'material-date-picker'
import './angular/app.js';